### ISSUE TITLE
How to use and config Linter

### ISSUE THREAD

**Issue by sipofwater** [chingu-voyage4/Geckos-Team-13#38]
Figure out how to use linting with create-react-app  
Document how to use in README.md  

https://groundberry.github.io/development/2017/06/11/create-react-app-linting-all-the-things.html

**Comment by sipofwater** [comment]
From Slack: forced semi-colons, ensuring vars are used if declared, cleaning up extra white space (end of line, extra lines)

**Comment by ghost** [comment]
For reference, In the first sprint we used:

https://standardjs.com/
&
https://github.com/standard/snazzy

Has all our wants except has a different opinion about semi-colons

**Comment by sipofwater** [comment]
Please, 3 spaces or more for indentation!  My eyes can't handle only 2, even with my colour coded indentation.

**Comment by sipofwater** [comment]
Removed snazzy and have eslint configured.  Did an initial linting to clean up the code and will submit a PR for it.
The rest of the linting errors will be cleaned up (or rule removed).
Tidied up a bit of the codebase as well (mostly indenting code)
