### ISSUE TITLE
feat: Create List

### ISSUE THREAD

**Issue by sipofwater** [chingu-voyage4/Geckos-Team-13#4]
User Stories:
====================================================
I can click on "Add a list" to add a new column and give it a name  
After I Save a new List, I can Add another immediately  
I can click on a List Title and Edit it  
I can delete Lists and **all** their Cards  
I can click on "Add a card" to add a new card  
I can see all cards that belongs to a List.  

Data Requirements:
====================================================
ID
List Title 
Board position (order)

**Comment by zealousAnemone** [comment]
Some user stories:

I can drag columns to rearrange them
I can click on "add a card" to add a new card
I can click on "add a list" to add a new column

**Comment by ghost** [comment]
User Stories:
====================================================
I can click on a list title and edit it 
I can access a list action menu in the top right. 
I can see all cards #5 that belongs to a list.

Functionality:
====================================================
Copy List 
Move List 
Follow 
Move all Cards in List 
Archive **all cards** in list 
Sort by 
- due date
- newest first
- oldest first
Archive list 

Data Requirements:
====================================================
List title 
Card 
Board position

**Comment by sipofwater** [comment]
@tiffanydevine @zealousAnemone , I have consolidated/edited/updated your contributions.
Let me know what you think!

**Comment by ghost** [comment]
@sipofwater : The first 2 user stories sound like board issues to me. If I try to think about what a list component would look like, I think these 2 stories would live one level up. 
Maybe....
```
<Board>
     <Column> 
           <List />
           <List />
     </Column>
</Board>
```

Of course List will also wrap card.

We are going to need to eventually reference the Column # (in order to move things around so if we separate the Column out as component, I think this will make our lives easier in the future. Thoughts?

**Comment by sipofwater** [comment]
@CollinPerkins is working on Board.  Collin, your thoughts?

**Comment by CollinPerkins** [comment]
I agree Copy list and Move List should be board.

**Comment by CollinPerkins** [comment]
Ive been looking into doing drag drop and nest.
