### ISSUE TITLE
feat: Create Card

### ISSUE THREAD

**Issue by sipofwater** [chingu-voyage4/Geckos-Team-13#5]
User Stories:
====================================================
I can add a card to a list and give it a name.
I can update the contents of a card and click save.

**Comment by sipofwater** [comment]
Drag and Drop from column to column to column

**Comment by zealousAnemone** [comment]
More user stories:

I can click on a card and view its contents
I can add a description for the card
I can add an attachment to the card
I can add a member to the card
I can add a label
I can add a checklist
I can add a due date
I can view attachments

**Comment by ghost** [comment]
User Stories:
====================================================
*This is for card view seen from the board - before expanding it*
I can see the card title 
I can see any labels associated with card
I can see all badges associated with card 
I can see members associated with card
**badges:**
- whether I am following (boolean)
- due date (flagged when date is close) 
- whether there is a description (boolean)
- comments (#)
- attachements (#) 
- checklist(number complete and total)

Functionality:
====================================================
When I hover on a card (in the list view), I can access a menu where I cam 
- edit labels
- add or change members associated with the card
- move the card to another board, list (column), or vertical position within a column  
- copy the card 
- change the due date 
- archive

Data Requirements:
====================================================
Card title 
Card Badges 
Card labels 
Members associated with the card 
Board that card belongs to (appears within the 'move' window
List that card belongs to 
Position within list

**Comment by sipofwater** [comment]
Once the expanded view of the card is removed, we can close this one off @mfarazahmad
