### ISSUE TITLE
I can click on a list title to edit it.

### ISSUE THREAD

**Issue by sipofwater** [chingu-voyage4/Geckos-Team-13#64]

**Comment by ghost** [comment]
This was something I implemented in the List component I submitted for the 2nd sprint

**Comment by sipofwater** [comment]
@tiffanydevine 
The only functionality I see missing is the ability to hit the enter key to save.  
We can capture that with this issue.

**Comment by ghost** [comment]
yup you are right. Its easy, I will add this afternoon and submit PR

**Comment by sipofwater** [comment]
I wish we had emoji's on here, plain text is boring!
I'll close off Issue #4 as complete since this issue captures the requirement.
thank you for taking this on @tiffanydevine !
